### ISSUE TITLE
skopeo copy from dir: to docker: causes failure

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/skopeo#329] opened 2017-04-21 14:23 UTC
```
$ wget -c https://kojipkgs.fedoraproject.org//packages/Fedora-Docker-Base/25/20170420.1/images/Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz

$ mkdir fedora-docker-base

$ tar -xvJf Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz -C fedora-docker-base

$ skopeo copy dir:/root/fedora-docker-base/ docker://localhost:5000/testingfedora
FATA[0000] runtime error: invalid memory address or nil pointer dereference
```

**Comment by runcom** [comment] 2017-04-21 14:34
nice, let me try and reproduce

**Comment by maxamillion** [comment] 2017-04-21 21:02
Now featuring debug output! :)

```
$ skopeo --debug copy dir:/root/fedora-docker-base/ docker://localhost:5000/testingfedora
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/atomic/sigstore
DEBU[0000] IsRunningImageAllowed for image dir:/root/fedora-docker-base
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
FATA[0000] runtime error: invalid memory address or nil pointer dereference
```

**Comment by runcom** [comment] 2017-04-23 11:09
@maxamillion which version of skopeo are you using?

**Comment by runcom** [comment] 2017-04-23 11:14
Wait, I've just realized the archive is a docker archive, which isn't going to work with the `dir:` transport as what's inside the extracted archive is not something skopeo can understand with `dir:`.

**Comment by runcom** [comment] 2017-04-23 11:23
in this case you'll need to use `docker-archive:` transport even if `tar.xz` isn't a supported format to load from. @cyphar could you chime in here?

**Comment by cyphar** [comment] 2017-04-24 05:00
Yeah, `dir:` doesn't mean what you think it means @maxamillion. It's an internal thing for `skopeo:` mainly used for testing purposes. I'm not sure what your `Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz` contains (is it an OCI image? a Docker image? just a rootfs?).

If it's a Docker image that's been `xz`d, you can use `docker-archive:`:

```
% unxz Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz
% skopeo copy docker-archive:Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz docker://localhost:5000/testingfedora
```

If it's an OCI image, you'd have to do something like this:

```
% tar -xvJf Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz -C fedora-docker-base
% skopeo copy oci:/root/fedora-docker-base/ docker://localhost:5000/testingfedora
```

If it's just a root filesystem you'll need to use another program to convert the root filesystem into an image. [`umoci`](https://github.com/openSUSE/umoci) can do this for you.

```
% umoci init --layout /tmp/fedora-docker-base
% umoci new --image /tmp/fedora-docker-base:latest
% umoci unpack --image /tmp/fedora-docker-base:latest /root/fedora-docker-base
% tar -xvJf Fedora-Docker-Base-25-20170420.1.x86_64.tar.xz -C /root/fedora-docker-base/rootfs
% umoci repack --image /tmp/fedora-docker-base:latest /root/fedora-docker-base
% skopeo copy oci:/tmp/fedora-docker-base:latest docker://localhost:5000/testingfedora
```

**Comment by mtrmac** [comment] 2017-04-24 16:59
It is a (docker save) archive, i.e. see `docker-archive:` above.

Nevertheless I would still like to fix the crash, but I can’t see it with current `master`:
```
FATA[0000] Error initializing image from source dir:/home/mitr/x/fedora-docker-base/: json: cannot unmarshal array into Go value of type image.manifestSchema1 
```

So, what version of skopeo is this?

(This error message is used because `manifest.GuessManifestMIMEType` fails, returning `""`, so `image.manifestInstanceFromBlob` defaults to schema1, and then we attempt to unmarshal the (docker save) manifest, which is an array, into a schema1 object. It’s not _immediately_ trivial to fix this, I suppose we could teach `GuessManifestMIMEType` to possibly fail with “definitely not a supported manifest”. Or, at least, `manifestSchema1FromManifest` could wrap the JSON error in “error decoding manifest” to give a bit more context. Longer-term it could make sense to make the (docker save) manifest a generally supported format through c/i/image, instead of hiding its existence in `docker/tarfile`, but it’s not quite obvious how to handle multiple named images with the c/i/image approacy.)

**Comment by maxamillion** [comment] 2017-04-25 15:03
Yeah, it's a docker-archive. I wasn't aware of that being a transport type.

```
skopeo-0.1.19-1.dev.git0224d8c.fc25.x86_64
```

**Comment by mtrmac** [comment] 2017-04-25 15:11
Thanks, reproduced. This was fixed in commit f89bd82dcd05a8e09b770bac00d5731c33db5cb1 , a few days after that release was cut.

**Comment by maxamillion** [comment] 2017-04-25 15:27
Thanks all! 👍

**Comment by runcom** [comment] 2017-04-25 15:34
I'll cut a new release later today, but I really want to have https://github.com/containers/image/pull/262 in it at least, @mtrmac wdyt?

**Comment by mtrmac** [comment] 2017-04-25 15:47
> I'll cut a new release later today, but I really want to have containers/image#262 in it at least, @mtrmac wdyt?

#262 is acceptable after it passes tests.  I'm afraid I haven't seriously looked at #261 yet, and I’m leaving in a few minutes so probably won't be able to review it until tomorrow at the earliest.

**Comment by runcom** [comment] 2017-04-25 15:52
Alright, let's postpone the release to end of the week or next week at latest.

**Comment by mtrmac** [comment] 2017-05-10 11:23
Available now as https://github.com/projectatomic/skopeo/releases/tag/v0.1.20 .

**Closed by mtrmac** 2017-05-10 11:23 UTC
