### ISSUE TITLE
'authorization required' error when trying to copy an image that does not exist

### ISSUE THREAD

**Issue by miabbott** [projectatomic/skopeo#235] opened 2016-10-19 13:48 UTC
Using the versions of `atomic` and `skopeo` in [CAHC](https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel), I observed the following error when trying to `atomic pull` an image that does not exist.

As a reminder, `atomic` is built from git master and `skopeo` is built from @mtrmac's 'integrate-all-the-things' branch in the CAHC stream.

```
# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.494 (2016-10-19 11:16:05)
        Commit: 42957b5cf0ded4bd919bd1b6d775fb22d93b69615f602876afbdfae89fc32d2d
        OSName: centos-atomic-host

  centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.435 (2016-10-13 19:12:30)
        Commit: 42c7ff310709ab1c97e5752a09de24053a98cc115239c784988d5c2bd2bfc9ba
        OSName: centos-atomic-host
-bash-4.2# rpm -q atomic skopeo
atomic-1.13.1.27-11468d40c48c12cf36c3d95769abed65a68d7f0a.dd4522961a9990fd47096ad652d3b6d9059051d7.el7.centos.x86_64
skopeo-1.14-66160a083bed5ec3b551eab62729c6ad5b0889aa.d684f1bc2399128bf8ca68a229c36385b0701806.el7.centos.x86_64
-bash-4.2# atomic --debug pull docker.io/this-does-not-exist
Image docker.io/this-does-not-exist is being pulled to docker ...
Pulling docker.io/library/this-does-not-exist:latest ...
Executing: /usr/bin/skopeo --debug copy --remove-signatures docker://docker.io/library/this-does-not-exist:latest docker-daemon:docker.io/this-does-not-exist:latest
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for docker.io/library/this-does-not-exist:latest 
DEBU[0000] IsRunningImageAllowed for image docker:docker.io/library/this-does-not-exist:latest 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ err <nil> 
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://registry-1.docker.io/v2/library/this-does-not-exist/manifests/latest 
DEBU[0000] docker-daemon: Closing tar stream to abort loading 
FATA[0000] Error initializing image from source docker://this-does-not-exist:latest: unauthorized: authentication required 

Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 65, in pull_image
    handler()
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 53, in pull_docker_image
    policy_filename=self.policy_filename)
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 371, in skopeo_copy
    return check_call(cmd)
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 136, in check_call
    return subprocess.check_call(cmd, env=env, stdin=stdin, stderr=stderr, stdout=stdout, close_fds=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/usr/bin/skopeo', '--debug', 'copy', '--remove-signatures', 'docker://docker.io/library/this-does-not-exist:latest', 'docker-daemon:docker.io/this-does-not-exist:latest']' returned non-zero exit status 1
```

**Comment by runcom** [comment] 2016-10-19 13:57
This is in line with what Docker does right now already. Meaning, in docker you see "not found" not because the registry V2 returned not found, but because the registry V2 returned unauthorized and the Docker engine fell back to V1 and V1 showed not found. 
This is different in skopeo because it doesn't have a fall back to V1 (we only support V2). And you see unauthorized because the V2 registry is designed not to leak info about whether an image is present on a registry or not. 
I would close this as not a bug. 

You can try it yourself with the Docker Hub first and then a private registry. 

docker pull runcom/doesntexist <- This shows not found from the Docker Hub becuase it has a V1 regisrey behind the scene and the fallback works

If you spin up a Docker V2 registry yourself 

docker pull privatereg.com/notexists <- here you get unauthorized

**Comment by runcom** [comment] 2016-10-19 14:00
Of course, with skopeo you get unauthorized because there's no fallback to V1, hence you get what the V2 regisrey actually returns, a unauthorized error.

**Closed** 2016-10-19 14:13 UTC

**Comment by miabbott** [comment] 2016-10-19 14:32
> And you see unauthorized because the V2 registry is designed not to leak info about whether an image is present on a registry or not. 

OK, that explains things.

I still think the error message is going to create confusion for end users, but not sure what else we could do about it given the design of the V2 registry.

**Comment by mtrmac** [comment] 2016-10-24 12:56
It seems plausibly possible to add extra code which, after receiving `unauthorized: authentication required`, heuristically tries to determine whether this is in fact an “image does not exist" error (by checking whether the V1 API is available, perhaps even hard-coding Docker Hub, and by using the V1 API if that can reliably disclose a nonexistent image). I can‘t work on that anytime soon, though.

**Comment by runcom** [comment] 2016-10-24 13:00
> It seems plausibly possible to add extra code which, after receiving unauthorized: authentication required, heuristically tries to determine whether this is in fact an “image does not exist" error

How would you try to determine if it's an image not found reliably? You can't exactly tell that afaict since it's how docker is designed. You still need to authenticate to your repository before saying it's an image not found.

Since docker doesn't handle this - meaning, it's just an ugly v1 fallback which will soon be deprecated and removed for good - I'd say let's leave this the way it is and don't bother to translate api error.

I'm going to write a blog post about this also.

**Comment by runcom** [comment] 2016-10-24 13:01
see also https://bugzilla.redhat.com/show_bug.cgi?id=1347805 - there's an upstream ongoing disccussion at https://github.com/docker/docker/issues/27281 but it won't likely be heard :)

**Comment by rhatdan** [comment] 2016-10-24 13:09
I agree, lets document it and move on, and hope V1 images disappear from the planet soon.

**Comment by mtrmac** [comment] 2016-10-24 18:20
Sure, nobody has time for this now; just pointing out that we might be able to do a bit better, for the benefit for possible future generations :) (FWIW migrating to v2 images won’t make this go away; it is a fundamental property of v2 registries.)
