### ISSUE TITLE
binary-local and default trust policy

### ISSUE THREAD

**Issue by amitsaha** [projectatomic/skopeo#200] opened 2016-09-12 05:50 UTC
When using a binary built via `binary-local` I get:

```
 $GOPATH/src/github.com/projectatomic/skopeo/skopeo copy docker://fedora:24 oci:fedora-24-oci
FATA[0000] Error loading trust policy: open /etc/containers/policy.json: no such file or directory
```
I can see why:

```
install: install-binary install-docs install-completions
    install -D -m 644 default-policy.json ${CONTAINERSSYSCONFIGDIR}/policy.json
```

I think this is a valid bug?

Workaround:

```
$ sudo mkdir -p /etc/containers
$ sudo cp default-policy.json /etc/containers/policy.json
```

**Comment by runcom** [comment] 2016-09-12 06:05
This is a duplicate of https://github.com/projectatomic/skopeo/issues/181 - pls continue the discussion over there

**Closed by runcom** 2016-09-12 06:05 UTC

**Comment by amitsaha** [comment] 2016-09-12 07:45
Thanks.
